### ISSUE TITLE
Validator: Plural time units error

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#180]
https://apps.axibase.com/chartlab/724a08aa

* `refresh-interval` can be expressed with time units.
* `update-interval` can be expressed as `time_unit` or `time_unitS`, with or without `s`.

Plugin flags both of these use cases.

**Comment by kghamilton89** [comment]
This is true for all time unit settings: https://apps.axibase.com/chartlab/9de7a626

**Comment by rodionos** [comment]
Refresh interval is incorrectly described in dictionary. It should defined in time units, not as number.

`refresh-interval = 5 second`

While the charts accepts plural units (as alias), the plugin is correct to raise error, because we may remove support for plural units in the future. Only singular units are acceptable.
