### ISSUE TITLE
Formatter: unexpected error

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#364]
```js
      script
        $("details").click(function(){
      		var commonCss = {height: 'auto', position:'static'};
            $(".axi-table-container, 
      .axi-table, 
      .axi-table-tbody, 
      .axi-table-tbody-row, 
      .axi-table-cell.axi-table-td").css(commonCss);
        });
      endscript
```

![Selection_001](https://user-images.githubusercontent.com/20650874/61128011-8774e200-a4b9-11e9-946a-40b622d7d065.png)

**Comment by PolinaShneider** [comment]
In the expression you use double quotes instead of slanted ones. Double quotes don't support multiline declarations. So it isn't valid jQuery code:

![image](https://user-images.githubusercontent.com/15448200/62449098-223ba600-b772-11e9-977d-b9413cca3651.png)

Esprima cannot parse it. I can make plugin give a more friendly warning.

**Comment by annstriganova** [comment]
The error must be catched and user must be informed, no errors in logs must be present.
